### ISSUE TITLE
License on fork

### ISSUE THREAD

**Issue by ettoreleandrotognoli** [FauconFan/mdbook-cmdrun#15]
Hello @FauconFan
I would like to start thanking you for this project

I have made a [fork](https://github.com/ettoreleandrotognoli/mdbook-ocirun) and did lot of changes to run the commands inside containers
I think this is not the proposition of this project, so I tough that would be better to rename it to ocirun

Now I'm not sure about what to do with the copyrights in the license, I found this [discussion](https://github.com/orgs/community/discussions/47161) saying that I should update the copyright

But in the license I found:
```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```
So I'm keeping the original copyright for now:
```
Copyright (c) 2022 Joseph Priou
```

Do you know what is the right to do?
Should I add new copyright only for the new files?

**Comment by FauconFan** [comment]
Hi @ettoreleandrotognoli !

Thank you for your interest, and well done on your fork!

Well, I am not a lawyer and what I write does not mean anything because I didn't spent 10000 hours on the topic. (hope you have the reference).

From my understanding, because the original repo is licensed with MIT, you can relicense any "copy" of the software, including removing my name and put yours instead. It's always nice to refer to the original author, but you don't "have to", not with a MIT license. It is not true for other licenses. If you do so, it means you are relicensing, and you are relicensing using the same license, because the author of the new license would be you.

I hope it is clearer.

I am closing this issue, because it is not a software issue, and people would find this if they are searching it.

Regards,
